// Step 3b of the pipeline: wire the native link + OAuth layer into the freshly
// scaffolded Android project. Runs AFTER `cap add android` (so Capacitor's
// defaults exist) and BEFORE gradle. Everything it writes is recorded in
// native-manifest.json so verify-native.mjs can gate the build.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { MARKER, OAUTH_HOSTS, OAUTH_PATHS, schemeFor, originOf } from "./native-config.mjs";

const {
  SITE_URL = "https://example.com",
  PACKAGE_ID = "app.sitely.generated",
  APP_NAME = "Sitely App",
} = process.env;

const assetManifest = JSON.parse(readFileSync("asset-manifest.json", "utf8"));
const native = assetManifest.native ?? {};
const scheme = native.redirect_scheme || schemeFor(PACKAGE_ID);
const origin = originOf(SITE_URL);
const host = new URL(SITE_URL).hostname;
const externalLinks = native.external_links || "in_app";

const javaDir = `android/app/src/main/java/${PACKAGE_ID.replace(/\./g, "/")}`;
mkdirSync(javaDir, { recursive: true });

const hostList = OAUTH_HOSTS.map((h) => `    "${h}",`).join("\n");
const pathList = OAUTH_PATHS.map((p) => `    "${p}",`).join("\n");

const java = `package ${PACKAGE_ID};

// ${MARKER} — generated by Sitely. Do not edit by hand.
//
// Link policy:
//   * ordinary links  -> stay inside this app's WebView (history preserved)
//   * OAuth links     -> Chrome Custom Tabs (Google blocks OAuth in WebViews)
//   * deep-link return-> forwarded back into the WebView on the site origin so
//                        the site sets its own session cookies in-app

import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.webkit.CookieManager;
import android.webkit.WebResourceRequest;
import android.webkit.WebSettings;
import android.webkit.WebView;

import androidx.browser.customtabs.CustomTabsIntent;

import com.getcapacitor.Bridge;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.BridgeWebViewClient;

public class MainActivity extends BridgeActivity {

  private static final String REDIRECT_SCHEME = "${scheme}";
  private static final String SITE_ORIGIN = "${origin}";
  private static final String SITE_HOST = "${host}";
  private static final int THEME_COLOR = 0xFF${(assetManifest.theme || "#4F46E5").replace("#", "").toUpperCase()};

  private static final String[] OAUTH_HOSTS = {
${hostList}
  };

  private static final String[] OAUTH_PATHS = {
${pathList}
  };

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    WebView webView = getBridge().getWebView();
    WebSettings settings = webView.getSettings();
    settings.setDomStorageEnabled(true);
    settings.setDatabaseEnabled(true);
    settings.setJavaScriptCanOpenWindowsAutomatically(true);
    settings.setSupportMultipleWindows(false);
    settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);

    // Google rejects OAuth from any user agent containing "wv"
    // (disallowed_useragent). Presenting a plain Chrome UA keeps every
    // non-OAuth page working and lets the Custom Tab hand-off look native.
    settings.setUserAgentString(stripWebViewMarker(settings.getUserAgentString()));

    CookieManager cookieManager = CookieManager.getInstance();
    cookieManager.setAcceptCookie(true);
    cookieManager.setAcceptThirdPartyCookies(webView, true);

    webView.setWebViewClient(new SitelyWebViewClient(getBridge()));

    handleDeepLink(getIntent());
  }

  @Override
  protected void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    setIntent(intent);
    handleDeepLink(intent);
  }

  @Override
  public void onPause() {
    super.onPause();
    CookieManager.getInstance().flush();
  }

  @Override
  public void onResume() {
    super.onResume();
    // Cookies written while the Custom Tab was in front are flushed to disk by
    // the browser; make sure our WebView reads the freshest jar it can.
    CookieManager.getInstance().flush();
  }

  @Override
  public void onBackPressed() {
    WebView webView = getBridge().getWebView();
    if (webView != null && webView.canGoBack()) {
      webView.goBack();
      return;
    }
    super.onBackPressed();
  }

  /** Returns the auth callback into the WebView, on the site's own origin. */
  private void handleDeepLink(Intent intent) {
    if (intent == null || intent.getData() == null) return;
    Uri data = intent.getData();
    String scheme = data.getScheme() == null ? "" : data.getScheme().toLowerCase();

    String target = null;
    if (REDIRECT_SCHEME.equals(scheme)) {
      String path = data.getPath() == null || data.getPath().isEmpty() ? "/" : data.getPath();
      String query = data.getQuery() == null ? "" : "?" + data.getQuery();
      String fragment = data.getFragment() == null ? "" : "#" + data.getFragment();
      target = SITE_ORIGIN + path + query + fragment;
    } else if (("http".equals(scheme) || "https".equals(scheme)) && SITE_HOST.equals(data.getHost())) {
      target = data.toString();
    }

    if (target == null) return;
    final String url = target;
    WebView webView = getBridge().getWebView();
    if (webView != null) {
      webView.post(new Runnable() {
        @Override
        public void run() {
          webView.loadUrl(url);
        }
      });
    }
  }

  private static String stripWebViewMarker(String ua) {
    if (ua == null || ua.isEmpty()) return ua;
    return ua.replace("; wv", "").replace(" wv)", ")").replace(" wv ", " ");
  }

  /** True when the provider has explicitly rejected an embedded user agent. */
  private static boolean isBlockedAgentUrl(Uri uri) {
    if (uri == null) return false;
    String full = uri.toString().toLowerCase();
    return full.contains("disallowed_useragent")
        || full.contains("/sorry/")
        || full.contains("error=embedded")
        || full.contains("browser_not_supported");
  }

  private static boolean isOAuthUrl(Uri uri) {
    if (uri == null) return false;
    String host = uri.getHost() == null ? "" : uri.getHost().toLowerCase();
    String path = uri.getPath() == null ? "" : uri.getPath().toLowerCase();
    String full = host + path;
    for (String candidate : OAUTH_HOSTS) {
      if (host.equals(candidate) || host.endsWith("." + candidate) || full.startsWith(candidate)) {
        return true;
      }
    }
    if (host.endsWith("google.com") || host.endsWith("googleapis.com")) {
      for (String p : OAUTH_PATHS) {
        if (path.startsWith(p) || path.contains(p)) return true;
      }
      if (path.contains("/signin") || path.contains("/oauth")) return true;
    }
    for (String p : OAUTH_PATHS) {
      if (path.startsWith(p)) return true;
    }
    return false;
  }

  private void openCustomTab(Uri uri) {
    CustomTabsIntent tabs = new CustomTabsIntent.Builder()
        .setShowTitle(true)
        .setUrlBarHidingEnabled(false)
        .setToolbarColor(THEME_COLOR)
        .build();
    tabs.intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    try {
      tabs.launchUrl(this, uri);
    } catch (Exception e) {
      // No browser able to host a Custom Tab: fall back to the system browser.
      // Still never the WebView — that path is what produces
      // disallowed_useragent.
      startActivity(new Intent(Intent.ACTION_VIEW, uri).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
    }
  }

  private class SitelyWebViewClient extends BridgeWebViewClient {
    SitelyWebViewClient(Bridge bridge) {
      super(bridge);
    }

    @Override
    public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
      Uri uri = request.getUrl();
      String scheme = uri.getScheme() == null ? "" : uri.getScheme().toLowerCase();

      if (REDIRECT_SCHEME.equals(scheme)) {
        handleDeepLink(new Intent(Intent.ACTION_VIEW, uri));
        return true;
      }

      // OAuth policy:
      //  * With the "wv" marker stripped from our user agent, Google accepts
      //    the sign-in flow in this WebView, which is the only lane that shares
      //    cookies with the site — so the post-login redirect lands back on the
      //    site already authenticated.
      //  * If a provider still refuses the embedded agent (it answers with
      //    disallowed_useragent / /sorry/), we hand that exact URL to Chrome
      //    Custom Tabs, and the custom-scheme deep link brings the user back.
      if (isBlockedAgentUrl(uri)) {
        openCustomTab(uri);
        return true;
      }

      if (isOAuthUrl(uri)) {
        view.loadUrl(uri.toString());
        return true;
      }

      if ("http".equals(scheme) || "https".equals(scheme)) {
        ${
          externalLinks === "external_browser"
            ? `boolean sameSite = uri.getHost() != null
            && (uri.getHost().equals(SITE_HOST) || uri.getHost().endsWith("." + SITE_HOST));
        if (!sameSite) {
          openCustomTab(uri);
          return true;
        }`
            : `// Every ordinary web link is loaded in this WebView, so back
        // navigation walks the in-app history instead of leaving the app.`
        }
        view.loadUrl(uri.toString());
        return true;
      }

      return super.shouldOverrideUrlLoading(view, request);
    }
  }
}
`;

writeFileSync(`${javaDir}/MainActivity.java`, java);
console.log(`Wrote ${javaDir}/MainActivity.java`);

// --- gradle: androidx.browser (Custom Tabs) ------------------------------
const gradlePath = "android/app/build.gradle";
let gradle = readFileSync(gradlePath, "utf8");
if (!gradle.includes("androidx.browser:browser")) {
  gradle = gradle.replace(
    /dependencies\s*\{/,
    (m) => `${m}\n    implementation "androidx.browser:browser:1.8.0" // ${MARKER}`,
  );
  writeFileSync(gradlePath, gradle);
}
if (!gradle.includes("androidx.browser:browser")) {
  throw new Error("Could not add androidx.browser dependency to app/build.gradle");
}
console.log("Patched app/build.gradle with androidx.browser:browser");

// --- manifest: deep link intent filters ---------------------------------
const manifestPath = "android/app/src/main/AndroidManifest.xml";
let manifest = readFileSync(manifestPath, "utf8");

if (/android:launchMode="[^"]*"/.test(manifest)) {
  manifest = manifest.replace(/android:launchMode="[^"]*"/, 'android:launchMode="singleTask"');
} else {
  manifest = manifest.replace(/<activity\s/, '<activity\n            android:launchMode="singleTask"\n            ');
}

if (!manifest.includes(`android:scheme="${scheme}"`)) {
  const filters = `
            <!-- ${MARKER}: OAuth return via custom scheme -->
            <intent-filter android:autoVerify="false">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${scheme}" />
            </intent-filter>
            <!-- ${MARKER}: OAuth return via https app link on the site host -->
            <intent-filter android:autoVerify="false">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="${host}" android:pathPrefix="/auth" />
            </intent-filter>
`;
  manifest = manifest.replace("</activity>", `${filters}        </activity>`);
}

// Android 11+ package visibility: needed to resolve a Custom Tabs provider.
if (!manifest.includes("android.support.customtabs.action.CustomTabsService")) {
  const queries = `
    <queries>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
`;
  manifest = manifest.replace("</manifest>", `${queries}</manifest>`);
}

writeFileSync(manifestPath, manifest);
console.log(`Patched AndroidManifest.xml (scheme ${scheme}://, https app link on ${host}/auth)`);

assetManifest.native = {
  ...native,
  marker: MARKER,
  redirect_scheme: scheme,
  site_origin: origin,
  site_host: host,
  external_links: externalLinks,
  app_name: APP_NAME,
  custom_tabs: true,
};
writeFileSync("asset-manifest.json", JSON.stringify(assetManifest, null, 2));
